import { WidgetPayload } from "../types";
import { COLORS } from "../constants";

// Estructura enriquecida para exportación a GENESIS
export interface ExportedWidget {
  version: string;
  widget: {
    type: string;
    props: Record<string, any>;
  };
  metadata: {
    id: string;
    createdAt: string;
    generatedBy: string;
    model: string;
  };
  styles: {
    colorScheme: 'dark' | 'light';
    primaryColor: string;
  };
}

// Generar UUID simple
const generateId = (): string => {
  return 'widget_' + Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
};

export const ExportService = {
  /**
   * Exportar widget como JSON enriquecido para GENESIS
   */
  exportJSON: (payload: WidgetPayload, model: string = 'gemini-3-flash'): ExportedWidget => {
    // Para layouts (stack, grid), incluir todas las propiedades del root
    const isLayout = payload.type === 'stack' || payload.type === 'grid';
    const widgetContent = isLayout
      ? { ...payload } // Incluir todo el objeto para layouts
      : { type: payload.type, props: payload.props }; // Solo type y props para widgets simples

    return {
      version: "1.0",
      widget: widgetContent as { type: string; props: Record<string, any> },
      metadata: {
        id: generateId(),
        createdAt: new Date().toISOString(),
        generatedBy: "NGX Studio",
        model: model
      },
      styles: {
        colorScheme: 'dark',
        primaryColor: COLORS.genesis
      }
    };
  },

  /**
   * Exportar como componente React standalone
   */
  exportReactComponent: (payload: WidgetPayload): string => {
    const componentName = payload.type
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');

    return `// Generated by NGX Studio - ${new Date().toISOString()}
// Widget: ${payload.type}

import React from 'react';

interface ${componentName}Props {
  data: ${JSON.stringify(payload.props, null, 2).replace(/"/g, '')};
  onAction?: (action: string, payload?: any) => void;
}

export const ${componentName}: React.FC<${componentName}Props> = ({ data, onAction }) => {
  return (
    <div className="widget-${payload.type}">
      {/* Widget content here */}
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
};

// Props para este widget:
export const defaultProps = ${JSON.stringify(payload.props, null, 2)};
`;
  },

  /**
   * Exportar como HTML embebible con estilos inline
   */
  exportHTML: (payload: WidgetPayload): string => {
    return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NGX Widget - ${payload.type}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body {
      background: #050505;
      font-family: 'Inter', sans-serif;
      padding: 20px;
    }
    .glass-card {
      background: linear-gradient(145deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.01) 100%);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 24px;
      padding: 20px;
      box-shadow: 0 8px 32px rgba(0,0,0,0.3);
    }
  </style>
</head>
<body>
  <div id="widget-container" class="glass-card">
    <!-- NGX Widget: ${payload.type} -->
    <div id="widget-data" style="display:none;">${JSON.stringify(payload)}</div>
    <pre class="text-white text-xs">${JSON.stringify(payload.props, null, 2)}</pre>
  </div>

  <script>
    // Widget data available for JavaScript
    window.NGX_WIDGET = ${JSON.stringify(payload)};
    console.log('[NGX Studio] Widget loaded:', window.NGX_WIDGET.type);
  </script>
</body>
</html>`;
  },

  /**
   * Descargar archivo
   */
  downloadFile: (content: string, filename: string, mimeType: string = 'application/json'): void => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  /**
   * Descargar widget como JSON
   */
  downloadJSON: (payload: WidgetPayload, model?: string): void => {
    const exported = ExportService.exportJSON(payload, model);
    const content = JSON.stringify(exported, null, 2);
    const filename = `ngx-widget-${payload.type}-${Date.now()}.json`;
    ExportService.downloadFile(content, filename, 'application/json');
  },

  /**
   * Descargar widget como HTML
   */
  downloadHTML: (payload: WidgetPayload): void => {
    const content = ExportService.exportHTML(payload);
    const filename = `ngx-widget-${payload.type}-${Date.now()}.html`;
    ExportService.downloadFile(content, filename, 'text/html');
  },

  /**
   * Copiar componente React al clipboard
   */
  copyReactComponent: async (payload: WidgetPayload): Promise<boolean> => {
    const content = ExportService.exportReactComponent(payload);
    try {
      await navigator.clipboard.writeText(content);
      return true;
    } catch (error) {
      console.error('Error copying to clipboard:', error);
      return false;
    }
  }
};
