import React from 'react';
import { LucideIcon } from 'lucide-react';
import { COLORS } from '../constants';

interface GlassCardProps {
  children: React.ReactNode;
  borderColor?: string;
  className?: string;
}

export const GlassCard: React.FC<GlassCardProps> = ({ children, borderColor = COLORS.nexus, className = "" }) => (
  <div className={`relative overflow-hidden rounded-3xl p-5 mb-3 animate-in ${className}`}
    style={{
      background: `linear-gradient(145deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.01) 100%)`,
      backdropFilter: 'blur(20px)',
      border: `1px solid ${COLORS.border}`,
      boxShadow: `0 8px 32px rgba(0,0,0,0.3), 0 0 0 1px ${borderColor}20`,
      animationFillMode: 'both'
    }}
  >
    <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[url('https://grainy-gradients.vercel.app/noise.svg')] bg-repeat mix-blend-overlay" />
    <div className="absolute inset-0 rounded-3xl pointer-events-none" style={{ background: `linear-gradient(to bottom right, rgba(255,255,255,0.1), transparent 60%)` }} />
    <div className="relative z-10">{children}</div>
  </div>
);

interface AgentBadgeProps {
  name: string;
  color: string;
  icon: LucideIcon;
}

export const AgentBadge: React.FC<AgentBadgeProps> = ({ name, color, icon: Icon }) => (
  <div className="flex items-center gap-2 mb-4 opacity-80">
    <div className="p-1.5 rounded-lg bg-white/5 border border-white/10" style={{ color }}>
      <Icon size={12} />
    </div>
    <span className="text-[10px] font-black tracking-[0.2em] uppercase" style={{ color }}>Generated by {name}</span>
  </div>
);

interface ProgressBarProps {
  value: number;
  max: number;
  color?: string;
  height?: number;
}

export const ProgressBar: React.FC<ProgressBarProps> = ({ value, max, color = COLORS.nexus, height = 6 }) => (
  <div className="w-full bg-white/10 rounded-full overflow-hidden" style={{ height }}>
    <div className="h-full rounded-full transition-all duration-500" style={{ width: `${Math.min((value / max) * 100, 100)}%`, background: color }} />
  </div>
);

interface ActionButtonProps {
  children: React.ReactNode;
  color?: string;
  onClick?: () => void;
  variant?: 'primary' | 'secondary';
}

export const ActionButton: React.FC<ActionButtonProps> = ({ children, color = COLORS.nexus, onClick, variant = 'primary' }) => (
  <button 
    onClick={onClick} 
    className={`w-full py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all ${variant === 'primary' ? 'text-white hover:opacity-90 shadow-lg' : 'bg-white/5 text-white/60 hover:bg-white/10'}`} 
    style={variant === 'primary' ? { background: `linear-gradient(135deg, ${color}, ${color}CC)` } : {}}
  >
    {children}
  </button>
);